server:
  port: 7003

eureka:
  instance:
    hostname: eureka-7003.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-7002.com:7002/eureka,http://eureka-7001.com:7001/eureka