server:
  port: 7002

eureka:
  instance:
    hostname: eureka-7002.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-7001.com:7001/eureka,http://eureka-7003.com:7003/eureka